### ISSUE TITLE
type error on delete-all

### ISSUE THREAD

**Issue by langston-barrett** [o2platform/digitalocean-cli#3]
```
do-cli delete-all
DigitalOcean CLI
----------------
/usr/lib/node_modules/digitalocean-cli/do-cli.coffee:85
      for (i = 0, len = ref.length; i < len; i++) {
                           ^
TypeError: Cannot read property 'length' of undefined
  at /usr/lib/node_modules/digitalocean-cli/do-cli.coffee:74:12
  at Request._callback (/usr/lib/node_modules/digitalocean-cli/node_modules/do-wrapper/lib/request_helper.js:32:7)
  at Request.self.callback (/usr/lib/node_modules/digitalocean-cli/node_modules/request/request.js:200:22)
  at emitTwo (events.js:106:13)
  at Request.emit (events.js:191:7)
  at Request.<anonymous> (/usr/lib/node_modules/digitalocean-cli/node_modules/request/request.js:1067:10)
  at emitOne (events.js:101:20)
  at Request.emit (events.js:188:7)
  at IncomingMessage.<anonymous> (/usr/lib/node_modules/digitalocean-cli/node_modules/request/request.js:988:12)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:926:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by DinisCruz** [comment]
Hi can you try now?, I just pushed a fix for it

**creating a droplet**
![image](https://cloud.githubusercontent.com/assets/656739/15986576/a9409106-3002-11e6-8de5-c36108199271.png)

**delete-all when there is an error on one of requests**
![image](https://cloud.githubusercontent.com/assets/656739/15986578/c7743e98-3002-11e6-8006-077ccf6d6a5c.png)

**delete-all working**

![image](https://cloud.githubusercontent.com/assets/656739/15986579/d0e4f774-3002-11e6-9898-d1afa966c153.png)
